"""
BioMistral Multilingual Pipeline Verification
Tests: Hindi transcript → English → BioMistral → Hindi SOAP + patient education
"""
from scriber_enhanced import ScribeAI

HINDI_TRANSCRIPT = (
    "मरीज को दो दिन से सिरदर्द और चक्कर आ रहे हैं। "
    "रक्तचाप 140/90 है। डॉक्टर ने पेरासिटामोल और आराम की सलाह दी।"
)

print("=" * 60)
print("BioMistral Multilingual Pipeline — Hindi Test")
print("=" * 60)
print(f"\nInput (Hindi):\n{HINDI_TRANSCRIPT}\n")

scribe = ScribeAI()

# ── Test 1: Hindi SOAP generation ──
print("► Step 1: Generating SOAP (Hindi → EN → BioMistral → Hindi)...")
success, soap = scribe.generate_soap_with_llm(HINDI_TRANSCRIPT, language="hi")

if success:
    print(f"\n✅ SOAP generated by: {soap.get('source', 'unknown')}")
    print(f"   Language: {soap.get('language', 'en')}\n")

    print("  [English — canonical]")
    print(f"    Subjective (EN): {soap.get('subjective_en', 'N/A')[:120]}")
    print(f"    Assessment (EN): {soap.get('assessment_en', 'N/A')[:120]}")
    print(f"    Plan (EN):       {soap.get('plan_en', 'N/A')[:120]}\n")

    print("  [Hindi — localized]")
    print(f"    Subjective (HI): {soap.get('subjective_localized', soap.get('subjective', 'N/A'))[:120]}")
    print(f"    Assessment (HI): {soap.get('assessment_localized', soap.get('assessment', 'N/A'))[:120]}")
    print(f"    Plan (HI):       {soap.get('plan_localized', soap.get('plan', 'N/A'))[:120]}")

    print(f"\n  ICD-10 Codes: {soap.get('icd10_codes', [])}")
else:
    print(f"\n❌ SOAP generation failed: {soap}")

# ── Test 2: Patient Education in Hindi ──
if success and soap:
    print("\n" + "=" * 60)
    print("► Step 2: Generating Patient Education in Hindi...")
    edu = scribe.generate_patient_education(soap, language="hi")
    print(f"\n  Patient Instructions (HI):\n{edu[:400]}")

print("\n" + "=" * 60)
print("Verification complete.")
